# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided this notice is
# preserved.  This file is offered as-is, without any warranty.
# Names of contributors must not be used to endorse or promote products
# derived from this file without specific prior written permission.


# See YAML format https://en.wikipedia.org/wiki/YAML
# See Travis CI (Continuous Integration) https://docs.travis-ci.com/


language: cpp
dist: xenial

os:
  - linux

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - clang
      - gcc
      - make
      - qt-sdk
      - qt5-qmake
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtdeclarative5-dev
      - qt5-default
      - qml-module-qtquick2
      - libqt5network5
      - libqt5sql5-sqlite
      - libqt5sql5-mysql
      - libqt5sql5-psql
script:
  - cd client/ultimate/
  - qmake catchchallenger-ultimate.pro
  - make
